# 项目相关配置
workflow:
  # 名称
  name: workflow-activiti-rest
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2020
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/uploadPath）
  profile: D:/workflow/uploadPath
  # 当前操作人
  operator: hruser # leaderuser

#日志配置
logging:
  path: I:/workspace/idea-workspace/workflow-activiti6/logs #保存日志
  config: classpath:logback-spring.xml
  lv: info # 控制台日志输出级别
  dateSize: 30 # 日志保存天数
